#DataSource Config
server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/photovoltaic?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 1qaz2wsx

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #开启日志
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

mengtu:
  push:
    sms:
      token: "svZM41#/"
  util:
    verificationcode:
      lifetime: 5
  obs:
    endpoint: "obs.cn-east-3.myhuaweicloud.com"
    access_key_id: "2SIVMNXYMCNZTWN5F6P1"
    secret_access_key: "RmUQlLIjldw5iHr9m6u2mtnOPm9ebJ9aFNxIyMMT"